modelog: debug
serverport: 8081

db:
  host: "postgres"
  port: 5432
  user: "admin"
  password: "admin"
  name: "messagio"

kafka:
  mode: "produce"
  host: "kafka-1"
  port: 9092
  topic: "messagio-topic"
